-- =========================================================================
-- 003: Platform tables (owner: gateway / sales_common)
-- ADK session tables are created by google-adk's DatabaseSessionService and
-- A2A task tables by a2a-sdk's DatabaseTaskStore; they are not managed here.
-- =========================================================================

-- Long-term conversational memory (sales_common.memory.PostgresMemoryService)
CREATE TABLE IF NOT EXISTS adk_memories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name    TEXT NOT NULL,
    user_id     TEXT NOT NULL,
    session_id  TEXT,
    event_id    TEXT,
    author      TEXT,
    text        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    tsv         TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', text)) STORED
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_adk_memories_event
    ON adk_memories(app_name, user_id, event_id) WHERE event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_adk_memories_scope ON adk_memories(app_name, user_id);
CREATE INDEX IF NOT EXISTS idx_adk_memories_tsv   ON adk_memories USING GIN (tsv);

-- Revoked gateway session tokens (tokens themselves are stateless signed values)
CREATE TABLE IF NOT EXISTS revoked_sessions (
    session_id  TEXT PRIMARY KEY,
    revoked_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
