-- =========================================================================
-- 005: Insertion-order sequence for the notification outbox.
-- created_at has one-second resolution, so rows enqueued in the same second
-- had no chronological order. The dispatcher orders by seq instead.
-- =========================================================================
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX IF NOT EXISTS idx_notif_pending_seq ON notifications(seq) WHERE status = 'pending';
