"""
PostgreSQL persistence for generated quotes/offers (``quotes`` table).

Stores every quote generated by ``generate_offer_quote`` so that:
- Returning customers can be shown their previous quotes.
- Orders can reference the original ``offer_id`` for audit trail.
- Quotes have a lifecycle: active -> ordered -> expired.

The schema lives in ``db/migrations/001_sales_schema.sql``; this module never
creates tables. All functions accept an optional ``conn`` so callers can join
an existing ``sales_common.db.transaction()``.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from psycopg import Connection

from sales_common import db
from sales_common.repositories.quotes import mark_ordered

from .logger import get_logger

logger = get_logger(__name__)

_UPSERT_SQL = """
INSERT INTO quotes
    (offer_id, customer_id, company_name, items_json, term_months,
     bant_score, subtotal, total_discount, total_price,
     monthly_total, yearly_total, full_quote_json, status,
     created_at, updated_at, expires_at)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (offer_id) DO UPDATE SET
    customer_id     = EXCLUDED.customer_id,
    company_name    = EXCLUDED.company_name,
    items_json      = EXCLUDED.items_json,
    term_months     = EXCLUDED.term_months,
    bant_score      = EXCLUDED.bant_score,
    subtotal        = EXCLUDED.subtotal,
    total_discount  = EXCLUDED.total_discount,
    total_price     = EXCLUDED.total_price,
    monthly_total   = EXCLUDED.monthly_total,
    yearly_total    = EXCLUDED.yearly_total,
    full_quote_json = EXCLUDED.full_quote_json,
    status          = EXCLUDED.status,
    created_at      = EXCLUDED.created_at,
    updated_at      = EXCLUDED.updated_at,
    expires_at      = EXCLUDED.expires_at
"""


def save_quote(
    quote_payload: Dict[str, Any],
    customer_id: Optional[str] = None,
    company_name: Optional[str] = None,
    *,
    conn: Optional[Connection] = None,
) -> Dict[str, str]:
    """Persist (upsert) a generated quote.

    ``quote_payload`` is the dict returned by ``generate_offer_quote``. Returns
    ``{"created_at", "expires_at"}`` (ISO-8601 UTC).
    """
    offer_id = quote_payload["offer_id"]
    now = db.now_iso()
    expires = db.compute_expires_at(now, "quote")
    params = (
        offer_id,
        customer_id,
        company_name,
        json.dumps(quote_payload.get("items", []), default=str),
        quote_payload.get("term_months", 12),
        quote_payload.get("bant_score", 0.0),
        quote_payload.get("subtotal", 0.0),
        quote_payload.get("total_discount", 0.0),
        quote_payload.get("total_price", 0.0),
        quote_payload.get("monthly_total", 0.0),
        quote_payload.get("yearly_total", 0.0),
        json.dumps(quote_payload, default=str),
        "active",
        now,
        now,
        expires,
    )
    if conn is not None:
        conn.execute(_UPSERT_SQL, params)
    else:
        with db.transaction() as own:
            own.execute(_UPSERT_SQL, params)
    logger.info("Quote %s saved for customer_id=%s, company=%s", offer_id, customer_id, company_name)
    return {"created_at": now, "expires_at": expires}


def load_quote(offer_id: str) -> Optional[Dict[str, Any]]:
    """Load a single quote by offer_id. Returns the parsed row or None."""
    row = db.fetch_one("SELECT * FROM quotes WHERE offer_id = %s", (offer_id,))
    return _row_to_dict(row) if row else None


def load_quotes_for_customer(
    customer_id: Optional[str] = None,
    company_name: Optional[str] = None,
    active_only: bool = True,
) -> List[Dict[str, Any]]:
    """Return quotes for a customer/company, newest first.

    At least one of ``customer_id`` or ``company_name`` must be provided.
    When ``active_only`` is True, expired and ordered quotes are excluded.
    """
    conditions: list[str] = []
    params: list[Any] = []
    if customer_id:
        conditions.append("customer_id = %s")
        params.append(customer_id)
    if company_name:
        conditions.append("LOWER(company_name) = LOWER(%s)")
        params.append(company_name)
    if not conditions:
        return []
    if active_only:
        conditions.append("status = 'active'")
        conditions.append("expires_at > %s")
        params.append(db.now_iso())

    where = " AND ".join(conditions)
    rows = db.fetch_all(f"SELECT * FROM quotes WHERE {where} ORDER BY created_at DESC", params)
    return [_row_to_dict(r) for r in rows]


def mark_quote_ordered(offer_id: str, conn: Optional[Connection] = None) -> bool:
    """Mark a quote as ordered (no longer active)."""
    return mark_ordered(offer_id, conn=conn)


def _row_to_dict(row: Dict[str, Any]) -> Dict[str, Any]:
    """Convert a DB row to a rich dict with the stored JSON parsed."""
    d = dict(row)
    try:
        d["full_quote"] = json.loads(d.pop("full_quote_json", None) or "{}")
    except (json.JSONDecodeError, TypeError):
        d["full_quote"] = {}
    try:
        d["items"] = json.loads(d.pop("items_json", None) or "[]")
    except (json.JSONDecodeError, TypeError):
        d["items"] = []
    return d
