"""
SQLite persistence layer for generated quotes/offers.

Stores every quote generated by ``generate_offer_quote`` so that:
- Returning customers can be shown their previous quotes.
- Orders can reference the original ``offer_id`` for audit trail.
- Quotes have a lifecycle: active → ordered → expired.

Tables
------
quotes – one row per generated quote (full JSON payload + metadata)
"""

import json
import os
import sqlite3
import threading
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from .logger import get_logger

logger = get_logger(__name__)

_DEFAULT_DB_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data")
_DEFAULT_DB_PATH = os.path.join(_DEFAULT_DB_DIR, "quotes.db")

_lock = threading.Lock()

# Quotes are valid for 30 days by default
_DEFAULT_EXPIRY_DAYS = 30


def _get_db_path() -> str:
    db_path = os.getenv("QUOTES_DB_PATH", _DEFAULT_DB_PATH)
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    return db_path


def _get_connection() -> sqlite3.Connection:
    conn = sqlite3.connect(_get_db_path())
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def init_db() -> None:
    """Create the quotes table if it doesn't exist."""
    with _lock:
        conn = _get_connection()
        try:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS quotes (
                    offer_id      TEXT PRIMARY KEY,
                    customer_id   TEXT,
                    company_name  TEXT,
                    items_json    TEXT NOT NULL,
                    term_months   INTEGER NOT NULL DEFAULT 12,
                    bant_score    REAL NOT NULL DEFAULT 0.0,
                    subtotal      REAL NOT NULL,
                    total_discount REAL NOT NULL DEFAULT 0.0,
                    total_price   REAL NOT NULL,
                    monthly_total REAL NOT NULL,
                    yearly_total  REAL NOT NULL,
                    full_quote_json TEXT NOT NULL,
                    status        TEXT NOT NULL DEFAULT 'active',
                    created_at    TEXT NOT NULL,
                    expires_at    TEXT NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_quotes_customer
                    ON quotes(customer_id);

                CREATE INDEX IF NOT EXISTS idx_quotes_company
                    ON quotes(company_name);

                CREATE INDEX IF NOT EXISTS idx_quotes_status
                    ON quotes(status);
            """)
            conn.commit()
            logger.info(f"Quotes database initialised at {_get_db_path()}")
        finally:
            conn.close()


def save_quote(
    quote_payload: Dict[str, Any],
    customer_id: str = None,
    company_name: str = None,
) -> None:
    """Persist a generated quote.  ``quote_payload`` is the dict returned by
    ``generate_offer_quote``."""
    offer_id = quote_payload["offer_id"]
    now = datetime.now().isoformat()
    expires = (datetime.now() + timedelta(days=_DEFAULT_EXPIRY_DAYS)).isoformat()

    with _lock:
        conn = _get_connection()
        try:
            conn.execute(
                """INSERT OR REPLACE INTO quotes
                   (offer_id, customer_id, company_name, items_json, term_months,
                    bant_score, subtotal, total_discount, total_price,
                    monthly_total, yearly_total, full_quote_json, status,
                    created_at, expires_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    offer_id,
                    customer_id,
                    company_name,
                    json.dumps(quote_payload.get("items", []), default=str),
                    quote_payload.get("term_months", 12),
                    quote_payload.get("bant_score", 0.0),
                    quote_payload.get("subtotal", 0.0),
                    quote_payload.get("total_discount", 0.0),
                    quote_payload.get("total_price", 0.0),
                    quote_payload.get("monthly_total", 0.0),
                    quote_payload.get("yearly_total", 0.0),
                    json.dumps(quote_payload, default=str),
                    "active",
                    now,
                    expires,
                ),
            )
            conn.commit()
            logger.info(f"Quote {offer_id} saved for customer_id={customer_id}, company={company_name}")
        finally:
            conn.close()


def load_quote(offer_id: str) -> Optional[Dict[str, Any]]:
    """Load a single quote by offer_id.  Returns the full quote payload or None."""
    with _lock:
        conn = _get_connection()
        try:
            row = conn.execute("SELECT * FROM quotes WHERE offer_id = ?", (offer_id,)).fetchone()
            if not row:
                return None
            return _row_to_dict(row)
        finally:
            conn.close()


def load_quotes_for_customer(
    customer_id: str = None,
    company_name: str = None,
    active_only: bool = True,
) -> List[Dict[str, Any]]:
    """Return quotes for a customer/company, newest first.

    At least one of ``customer_id`` or ``company_name`` must be provided.
    When ``active_only`` is True, expired and ordered quotes are excluded.
    """
    conditions = []
    params: list = []
    if customer_id:
        conditions.append("customer_id = ?")
        params.append(customer_id)
    if company_name:
        conditions.append("LOWER(company_name) = LOWER(?)")
        params.append(company_name)
    if not conditions:
        return []
    if active_only:
        conditions.append("status = 'active'")
        conditions.append("expires_at > ?")
        params.append(datetime.now().isoformat())

    where = " AND ".join(conditions)
    with _lock:
        conn = _get_connection()
        try:
            rows = conn.execute(
                f"SELECT * FROM quotes WHERE {where} ORDER BY created_at DESC",
                params,
            ).fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def mark_quote_ordered(offer_id: str) -> bool:
    """Mark a quote as ordered (no longer active)."""
    with _lock:
        conn = _get_connection()
        try:
            cur = conn.execute(
                "UPDATE quotes SET status = 'ordered' WHERE offer_id = ?",
                (offer_id,),
            )
            conn.commit()
            return cur.rowcount > 0
        finally:
            conn.close()


def _row_to_dict(row: sqlite3.Row) -> Dict[str, Any]:
    """Convert a DB row to a rich dict with the full_quote_json parsed."""
    d = {k: row[k] for k in row.keys()}
    # Parse stored JSON back to dicts
    try:
        d["full_quote"] = json.loads(d.pop("full_quote_json", "{}"))
    except (json.JSONDecodeError, TypeError):
        d["full_quote"] = {}
    try:
        d["items"] = json.loads(d.pop("items_json", "[]"))
    except (json.JSONDecodeError, TypeError):
        d["items"] = []
    return d


# Auto-initialise on import
init_db()
