#!/usr/bin/env python3
"""Export the legacy SQLite demo database to PostgreSQL seed SQL.

One-time migration helper (already run; output committed): reads the legacy
unified SQLite DB ``SuperAgent/data/sales_agent.db``. That file was removed from
the repository; recover it with
``git show b3cb18a:SuperAgent/data/sales_agent.db > /tmp/sales_agent.db`` and pass
``--sqlite /tmp/sales_agent.db`` and writes ``db/seed/001_sales_data.sql`` with INSERT
statements matching ``db/migrations/001_sales_schema.sql``.

Usage::

    python scripts/export_sqlite_seed.py [--sqlite PATH] [--out PATH]
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Table order respects foreign keys.
TABLES = [
    "accounts", "contacts", "spend", "opportunities", "insights", "actions",
    "quotes", "carts", "cart_items", "orders", "order_items",
    "payments", "payment_events", "payment_rate_limit", "customer_payment_methods",
    "fulfillments", "customer_master", "notifications", "dedup_cache",
]
# Legacy SQLite column spellings -> PostgreSQL quoted identifiers.
RENAMES = {
    "accounts": {"industry": "Industry", "street": "Street", "city": "City", "state": "State", "website": "Website"},
}
IDENTITY_TABLES = {"cart_items", "order_items"}
# (child column, parent table, parent column): SQLite never enforced these FKs, so
# legacy rows can be orphaned; PostgreSQL enforces them, so orphans are skipped.
FOREIGN_KEYS = {
    "cart_items": [("cart_id", "carts", "cart_id")],
    "orders": [("offer_id", "quotes", "offer_id")],
    "order_items": [("order_id", "orders", "order_id")],
    "payments": [("order_id", "orders", "order_id")],
    "payment_events": [("payment_id", "payments", "payment_id")],
    "fulfillments": [("order_id", "orders", "order_id")],
    "customer_master": [("first_order_id", "orders", "order_id")],
}


def literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, bytes):
        value = value.decode("utf-8", errors="replace")
    return "'" + str(value).replace("'", "''") + "'"


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def export(sqlite_path: Path, out_path: Path) -> dict[str, int]:
    src = sqlite3.connect(sqlite_path)
    src.row_factory = sqlite3.Row
    existing = {r[0] for r in src.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    counts: dict[str, int] = {}
    skipped: dict[str, int] = {}
    exported_keys: dict[tuple[str, str], set] = {}
    lines = [
        "-- Seed data exported from the legacy SQLite demo database (sales_agent.db).",
        "-- Generated by scripts/export_sqlite_seed.py. Applied once (seed_versions).",
        "SET client_min_messages = warning;",
        "",
    ]
    for table in TABLES:
        if table not in existing:
            counts[table] = 0
            continue
        rows = src.execute(f"SELECT * FROM {table}").fetchall()
        kept = []
        for row in rows:
            orphan = any(
                row[col] is not None and row[col] not in exported_keys.get((parent, pcol), set())
                for col, parent, pcol in FOREIGN_KEYS.get(table, [])
            )
            if orphan:
                skipped[table] = skipped.get(table, 0) + 1
            else:
                kept.append(row)
        rows = kept
        counts[table] = len(rows)
        for col in rows[0].keys() if rows else []:
            exported_keys[(table, col)] = {r[col] for r in rows}
        if not rows:
            continue
        renames = RENAMES.get(table, {})
        cols = [renames.get(c.lower(), c) if c.lower() in renames else c for c in rows[0].keys()]
        col_sql = ", ".join(quote_ident(c) for c in cols)
        lines.append(f"-- {table}: {len(rows)} rows")
        for row in rows:
            values = ", ".join(literal(row[k]) for k in row.keys())
            lines.append(f"INSERT INTO {table} ({col_sql}) VALUES ({values}) ON CONFLICT DO NOTHING;")
        if table in IDENTITY_TABLES:
            lines.append(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                f"COALESCE((SELECT MAX(id) FROM {table}), 1));"
            )
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    for table, n in skipped.items():
        print(f"skipped {n} orphaned {table} row(s) (missing parent)")
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sqlite", type=Path, default=ROOT / "SuperAgent/data/sales_agent.db")
    parser.add_argument("--out", type=Path, default=ROOT / "db/seed/001_sales_data.sql")
    args = parser.parse_args()
    counts = export(args.sqlite, args.out)
    for table, n in counts.items():
        print(f"{table:28s} {n}")
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
