"""Generate ``db/seed/002_catalog.sql`` from the legacy product dicts.

Sources (read as Python source and evaluated with ``ast.literal_eval``, so no
agent package is imported and no ``GEMINI_MODEL`` / ADK setup is needed):

* ``PRODUCT_CATALOG``    - ProductAgent/product_agent/tools/product_tools.py
* ``PRODUCT_PRICE_BOOK`` - OfferManagement/offer_management/tools/pricing_tools.py

The ProductAgent tool module was removed when the catalog moved to
``services/catalog``; by default the script reads it from git history
(``--catalog-rev``, default ``HEAD``) when the working-tree file is missing.

Usage::

    python scripts/export_catalog_seed.py            # writes db/seed/002_catalog.sql
    python scripts/export_catalog_seed.py --stdout   # print instead
"""

from __future__ import annotations

import argparse
import ast
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CATALOG_SRC = "ProductAgent/product_agent/tools/product_tools.py"
PRICE_SRC = "OfferManagement/offer_management/tools/pricing_tools.py"
OUT = REPO / "db" / "seed" / "002_catalog.sql"

# Keys stripped from legacy product records (pricing lives in unit_price).
_DROP_KEYS = {"price"}


def _read_source(rel_path: str, rev: str) -> str:
    path = REPO / rel_path
    if path.is_file():
        return path.read_text(encoding="utf-8")
    try:
        return subprocess.run(
            ["git", "-C", str(REPO), "show", f"{rev}:{rel_path}"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        raise SystemExit(f"Cannot read {rel_path} (working tree or git {rev}): {exc}") from exc


def _literal(source: str, name: str):
    """Return the literal value assigned to module-level ``name`` in ``source``."""
    for node in ast.parse(source).body:
        targets = []
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            targets = [node.target]
        for target in targets:
            if isinstance(target, ast.Name) and target.id == name:
                return ast.literal_eval(node.value)
    raise SystemExit(f"{name} not found")


def load_catalog(rev: str = "HEAD") -> tuple[dict, dict]:
    catalog = _literal(_read_source(CATALOG_SRC, rev), "PRODUCT_CATALOG")
    price_book = _literal(_read_source(PRICE_SRC, rev), "PRODUCT_PRICE_BOOK")
    return catalog, price_book


def _q(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return f"{value:.2f}"
    return "'" + str(value).replace("'", "''") + "'"


def _jsonb(value) -> str:
    return _q(json.dumps(value, ensure_ascii=False)) + "::jsonb"


def render(catalog: dict, price_book: dict) -> str:
    missing = sorted(set(catalog) ^ set(price_book))
    if missing:
        raise SystemExit(f"Catalog and price book disagree on SKUs: {missing}")
    rows = []
    for order, (pid, product) in enumerate(catalog.items(), start=1):
        record = {k: v for k, v in product.items() if k not in _DROP_KEYS}
        price = price_book[pid]
        rows.append(
            "    ("
            + ", ".join(
                [
                    _q(pid.upper()),
                    _q(record["product_name"]),
                    _q(record["category"]),
                    _q(record["technology"]),
                    _jsonb(record.get("speeds", {})),
                    _q(record.get("description", "")),
                    _jsonb(record.get("features", [])),
                    _q(bool(record.get("available", True))),
                    _q(float(price["unit_price"])),
                    _q(price["family"]),
                    str(order * 10),
                ]
            )
            + ")"
        )
    return (
        "-- =========================================================================\n"
        "-- 002: Product catalog seed (16 SKUs)\n"
        "-- GENERATED by scripts/export_catalog_seed.py from the legacy PRODUCT_CATALOG\n"
        "-- (ProductAgent) and PRODUCT_PRICE_BOOK (OfferManagement). Do not edit by hand.\n"
        "-- Idempotent: re-running updates existing rows.\n"
        "-- =========================================================================\n\n"
        "INSERT INTO products (product_id, product_name, category, technology, speeds,\n"
        "                      description, features, available, unit_price, family, sort_order)\n"
        "VALUES\n"
        + ",\n".join(rows)
        + "\nON CONFLICT (product_id) DO UPDATE SET\n"
        "    product_name = EXCLUDED.product_name,\n"
        "    category     = EXCLUDED.category,\n"
        "    technology   = EXCLUDED.technology,\n"
        "    speeds       = EXCLUDED.speeds,\n"
        "    description  = EXCLUDED.description,\n"
        "    features     = EXCLUDED.features,\n"
        "    available    = EXCLUDED.available,\n"
        "    unit_price   = EXCLUDED.unit_price,\n"
        "    family       = EXCLUDED.family,\n"
        "    sort_order   = EXCLUDED.sort_order;\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--stdout", action="store_true", help="print SQL instead of writing the file")
    parser.add_argument("--catalog-rev", default="HEAD", help="git revision for removed source files")
    args = parser.parse_args(argv)
    catalog, price_book = load_catalog(args.catalog_rev)
    sql = render(catalog, price_book)
    if args.stdout:
        sys.stdout.write(sql)
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(sql, encoding="utf-8")
        print(f"Wrote {OUT.relative_to(REPO)} ({len(catalog)} products)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
